const express=require('express');
const {query,transaction}=require('../db');
const router=express.Router();
function attach(requireAuth,requireManager){
 const owner=requireManager;
 const staff=roles=>requireAuth(async(req,res,next)=>{if(!roles.includes(req.user.role))return res.status(403).json({ok:false,message:'صلاحية الإدارة مطلوبة.'});next();});
 router.get('/app-settings',requireAuth,async(req,res,next)=>{try{if(req.user.role!=='owner')return res.status(403).json({ok:false});const r=await query('SELECT key,value,updated_at,updated_by FROM app_settings ORDER BY key');res.json({ok:true,items:r.rows});}catch(e){next(e)}});router.put('/app-settings',requireAuth,async(req,res,next)=>{try{if(req.user.role!=='owner')return res.status(403).json({ok:false});const input=req.body&&typeof req.body==='object'?req.body:{};const entries=[];for(const [key,value] of Object.entries(input)){if(!/^[a-zA-Z0-9_.-]{1,120}$/.test(key))continue;entries.push([key,value]);}await transaction(async c=>{for(const [key,value] of entries)await c.query(`INSERT INTO app_settings(key,value,updated_by,updated_at) VALUES($1,$2,$3,NOW()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_by=EXCLUDED.updated_by,updated_at=NOW()`,[key,JSON.stringify(value),req.user.id])});await query(`INSERT INTO audit_logs(actor_user_id,action,target_type,details) VALUES($1,'settings_update','app_settings',$2)`,[req.user.id,JSON.stringify({keys:entries.map(x=>x[0])})]);res.json({ok:true,updated:entries.map(x=>x[0])});}catch(e){next(e)}});router.get('/admin/dashboard',staff(['admin','owner']),async(req,res,next)=>{try{const names=['users','posts','conversations','reports','registrations'];const out={};for(const n of names){const r=await query('SELECT COUNT(*)::int count FROM '+n);out[n]=r.rows[0].count}res.json({ok:true,stats:out})}catch(e){next(e)}});
 router.get('/admin/users',staff(['admin','owner']),async(req,res,next)=>{try{const r=await query('SELECT id,full_name,student_id,role,is_active,last_seen_at,created_at FROM users ORDER BY created_at DESC LIMIT 300');res.json({ok:true,items:r.rows})}catch(e){next(e)}});
 router.patch('/admin/users/:id/status',staff(['admin','owner']),async(req,res,next)=>{try{const id=Number(req.params.id),active=req.body?.is_active===true;await query("UPDATE users SET is_active=$1 WHERE id=$2 AND role<>'owner'",[active,id]);await query('DELETE FROM sessions WHERE user_id=$1',[id]);res.json({ok:true})}catch(e){next(e)}});
 router.get('/admin/registrations',staff(['admin','owner']),async(req,res,next)=>{try{const r=await query("SELECT r.*,c.risk_level,c.score,c.flags FROM registrations r LEFT JOIN LATERAL (SELECT risk_level,score,flags FROM registration_checks rc WHERE rc.registration_id=r.id ORDER BY rc.id DESC LIMIT 1)c ON TRUE WHERE r.status='pending' ORDER BY r.created_at DESC LIMIT 300");res.json({ok:true,items:r.rows})}catch(e){next(e)}});
 router.patch('/admin/registrations/:id',staff(['admin','owner']),async(req,res,next)=>{try{const id=Number(req.params.id),status=String(req.body?.status||'');if(!['approved','rejected','archived'].includes(status))return res.status(400).json({ok:false});await transaction(async c=>{const r=await c.query('SELECT id FROM registrations WHERE id=$1 FOR UPDATE',[id]);if(!r.rowCount)throw Object.assign(new Error('NOT_FOUND'),{code:'NOT_FOUND'});await c.query('UPDATE registrations SET status=$1,reviewed_by=$2,reviewed_at=NOW(),rejection_reason=$3 WHERE id=$4',[status,req.user.id,status==='rejected'?(req.body?.rejection_reason||'مرفوض'):null,id])});res.json({ok:true,status})}catch(e){if(e.code==='NOT_FOUND')return res.status(404).json({ok:false});next(e)}});
 router.get('/admin/reports',staff(['admin','owner']),async(req,res,next)=>{try{const r=await query('SELECT id,reporter_id,target_type,target_id,reason,details,status,created_at FROM reports ORDER BY created_at DESC LIMIT 300');res.json({ok:true,items:r.rows})}catch(e){next(e)}});
 router.patch('/admin/reports/:id',staff(['admin','owner']),async(req,res,next)=>{try{await query('UPDATE reports SET status=$1,reviewed_by=$2,reviewed_at=NOW() WHERE id=$3',[String(req.body?.status||'reviewed'),req.user.id,Number(req.params.id)]);res.json({ok:true})}catch(e){next(e)}});
 router.get('/admin/chats',staff(['admin','owner']),async(req,res,next)=>{try{const r=await query('SELECT id,name,type,is_private,messaging_paused,created_at FROM conversations ORDER BY created_at DESC LIMIT 200');res.json({ok:true,items:r.rows})}catch(e){next(e)}});
 router.patch('/admin/chats/:id',staff(['admin','owner']),async(req,res,next)=>{try{await query('UPDATE conversations SET messaging_paused=$1 WHERE id=$2',[req.body?.messaging_paused===true,Number(req.params.id)]);res.json({ok:true})}catch(e){next(e)}});
 router.post('/admin/content',staff(['admin','owner']),async(req,res,next)=>{try{const type=String(req.body?.type||'announcement'),title=String(req.body?.title||'').trim(),body=String(req.body?.body||'').trim();if(!title||!body)return res.status(400).json({ok:false});if(type==='activity'){const r=await query('INSERT INTO activities(title,body,tag,event_date,location) VALUES($1,$2,$3,$4,$5) RETURNING id',[title,body,String(req.body?.tag||'').slice(0,50),req.body?.event_date?new Date(req.body.event_date):null,String(req.body?.location||'').slice(0,255)]);return res.status(201).json({ok:true,id:Number(r.rows[0].id)})}const r=await query('INSERT INTO announcements(title,body,tag) VALUES($1,$2,$3) RETURNING id',[title,body,String(req.body?.tag||'').slice(0,50)]);res.status(201).json({ok:true,id:Number(r.rows[0].id)})}catch(e){next(e)}});
 router.get('/owner/status',requireAuth,async(req,res,next)=>{try{if(req.user.role!=='owner')return res.status(403).json({ok:false});res.json({ok:true,owner:{id:Number(req.user.id),name:req.user.full_name,role:req.user.role}})}catch(e){next(e)}});
 router.get('/owner/users',requireAuth,async(req,res,next)=>{try{if(req.user.role!=='owner')return res.status(403).json({ok:false});const r=await query('SELECT id,full_name,student_id,email,phone,academic_year,role,is_active,last_seen_at,created_at FROM users ORDER BY id DESC LIMIT 500');res.json({ok:true,items:r.rows})}catch(e){next(e)}});
 router.patch('/owner/users/:id/role',requireAuth,async(req,res,next)=>{try{if(req.user.role!=='owner')return res.status(403).json({ok:false});const id=Number(req.params.id),role=String(req.body?.role||'member');if(!['member','admin'].includes(role))return res.status(400).json({ok:false,message:'الدور غير صالح.'});const target=await query('SELECT role FROM users WHERE id=$1',[id]);if(!target.rowCount)return res.status(404).json({ok:false,message:'المستخدم غير موجود.'});if(target.rows[0].role==='owner')return res.status(409).json({ok:false,message:'لا يمكن تغيير دور مالك النظام.'});await query('UPDATE users SET role=$1 WHERE id=$2',[role,id]);await query(`INSERT INTO audit_logs(actor_user_id,action,target_type,target_id,details) VALUES($1,'role_update','user',$2,$3)`,[req.user.id,id,JSON.stringify({role})]);res.json({ok:true,id,role});}catch(e){next(e)}});router.get('/owner/activity',requireAuth,async(req,res,next)=>{try{if(req.user.role!=='owner')return res.status(403).json({ok:false});const r=await query('SELECT ua.*,u.full_name FROM user_activity ua JOIN users u ON u.id=ua.user_id ORDER BY ua.last_activity_at DESC LIMIT 200');res.json({ok:true,items:r.rows})}catch(e){next(e)}});
 router.get('/owner/audit',requireAuth,async(req,res,next)=>{try{if(req.user.role!=='owner')return res.status(403).json({ok:false});const r=await query('SELECT a.*,u.full_name FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.created_at DESC LIMIT 300');res.json({ok:true,items:r.rows})}catch(e){next(e)}});
 router.get('/owner/database-summary',requireAuth,async(req,res,next)=>{try{if(req.user.role!=='owner')return res.status(403).json({ok:false});const names=['users','registrations','posts','conversations','messages','user_activity','activity_events','reports','audit_logs','app_settings'];const out={};for(const n of names){const r=await query('SELECT COUNT(*)::int count FROM '+n);out[n]=r.rows[0].count}res.json({ok:true,tables:out})}catch(e){next(e)}});
 router.get('/owner/database/:table',requireAuth,async(req,res,next)=>{try{if(req.user.role!=='owner')return res.status(403).json({ok:false});const allowed=new Set(['users','registrations','posts','post_likes','post_comments','conversations','conversation_members','messages','user_activity','activity_events','reports','audit_logs','agent_actions','app_settings']);const table=String(req.params.table);if(!allowed.has(table))return res.status(404).json({ok:false});const r=await query('SELECT * FROM '+table+' ORDER BY 1 DESC LIMIT 120');res.json({ok:true,table,rows:r.rows})}catch(e){next(e)}});
 router.post('/owner/agent-actions',owner,async(req,res,next)=>{try{const a=req.body&&typeof req.body==='object'?req.body:{};if(!a.action_type)return res.status(400).json({ok:false,message:'action_type is required.'});const r=await query('INSERT INTO agent_actions(actor_user_id,action_type,target_type,target_id,details,status) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,created_at',[req.user.id,String(a.action_type).slice(0,120),a.target_type?String(a.target_type).slice(0,60):null,a.target_id==null?null:Number(a.target_id),JSON.stringify(a.details||{}),String(a.status||'completed').slice(0,30)]);res.status(201).json({ok:true,action:{id:Number(r.rows[0].id),created_at:r.rows[0].created_at}})}catch(e){next(e)}});
 return router;
}
module.exports={router,attach};