const express = require('express');
const { query, transaction, notify } = require('../db');
const router = express.Router();
function attach(getUser, requireAuth) {
  async function ensureGeneral(user){const general=await query("SELECT id FROM conversations WHERE type='official' AND name='الغرفة العامة' LIMIT 1");if(!general.rowCount)return null;await query("INSERT INTO conversation_members(conversation_id,user_id,role) VALUES($1,$2,'member') ON CONFLICT DO NOTHING",[general.rows[0].id,user.id]);return Number(general.rows[0].id);}
  router.get('/chats',requireAuth,async(req,res,next)=>{try{await ensureGeneral(req.user);const r=await query(`SELECT c.*,cm.role,cm.is_muted,cm.last_read_message_id,(SELECT m.body FROM messages m WHERE m.conversation_id=c.id ORDER BY m.id DESC LIMIT 1) AS last_message,(SELECT m.created_at FROM messages m WHERE m.conversation_id=c.id ORDER BY m.id DESC LIMIT 1) AS last_message_at FROM conversation_members cm JOIN conversations c ON c.id=cm.conversation_id WHERE cm.user_id=$1 ORDER BY COALESCE(last_message_at,c.created_at) DESC,c.id DESC`,[req.user.id]);res.json({ok:true,items:r.rows.map(x=>({...x,id:Number(x.id)}))});}catch(e){next(e)}});
  router.post('/chats',requireAuth,async(req,res,next)=>{try{const name=String(req.body?.name||'').trim().slice(0,150);if(!name)return res.status(400).json({ok:false,message:'اسم الغرفة مطلوب.'});const type=req.body?.type==='official'&&req.user.role!=='owner'?'group':(req.body?.type||'group'),isPrivate=Boolean(req.body?.is_private);const created=await transaction(async client=>{const c=await client.query('INSERT INTO conversations(name,description,type,is_private,created_by,host_user_id) VALUES($1,$2,$3,$4,$5,$5) RETURNING id',[name,String(req.body?.description||'').slice(0,1000),type,isPrivate,req.user.id]);await client.query("INSERT INTO conversation_members(conversation_id,user_id,role) VALUES($1,$2,'host')",[c.rows[0].id,req.user.id]);return c.rows[0];});res.status(201).json({ok:true,chat:{id:Number(created.id),name,type,is_private:isPrivate}});}catch(e){next(e)}});
  router.post('/chats/:id/join',requireAuth,async(req,res,next)=>{try{const id=Number(req.params.id),c=await query('SELECT * FROM conversations WHERE id=$1',[id]);if(!c.rowCount)return res.status(404).json({ok:false,message:'الغرفة غير موجودة.'});if(c.rows[0].is_private&&req.user.role==='member')return res.status(403).json({ok:false,message:'هذه الغرفة خاصة.'});await query("INSERT INTO conversation_members(conversation_id,user_id,role) VALUES($1,$2,'member') ON CONFLICT DO NOTHING",[id,req.user.id]);res.json({ok:true});}catch(e){next(e)}});
  router.get('/chats/:id/messages',requireAuth,async(req,res,next)=>{try{const id=Number(req.params.id),member=await query('SELECT 1 FROM conversation_members WHERE conversation_id=$1 AND user_id=$2',[id,req.user.id]);if(!member.rowCount)return res.status(403).json({ok:false,message:'لست عضواً في الغرفة.'});const limit=Math.min(Math.max(Number(req.query.limit)||30,1),50),before=req.query.before?new Date(req.query.before):null;const r=await query(`SELECT m.*,u.full_name,u.avatar_media_id,u.avatar_url FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.conversation_id=$1 AND ($3::timestamptz IS NULL OR m.created_at<$3) ORDER BY m.created_at DESC,m.id DESC LIMIT $2`,[id,limit,before]);res.json({ok:true,items:r.rows.reverse().map(x=>({...x,id:Number(x.id),conversation_id:Number(x.conversation_id),sender_id:Number(x.sender_id),media_url:x.media_id?`/api/media/${x.media_id}`:(x.image_url||null),audio_url:x.audio_media_id?`/api/media/${x.audio_media_id}`:(x.audio_url||null),avatar_url:x.avatar_media_id?`/api/media/${x.avatar_media_id}`:(x.avatar_url||null)}))});}catch(e){next(e)}});
  router.post('/chats/:id/messages',requireAuth,async(req,res,next)=>{try{const id=Number(req.params.id),body=String(req.body?.body||'').trim().slice(0,4000),mediaId=req.body?.media_id?Number(req.body.media_id):null,audioId=req.body?.audio_media_id?Number(req.body.audio_media_id):null;if(!body&&!mediaId&&!audioId)return res.status(400).json({ok:false,message:'الرسالة فارغة.'});const member=await query('SELECT is_muted FROM conversation_members WHERE conversation_id=$1 AND user_id=$2',[id,req.user.id]);if(!member.rowCount)return res.status(403).json({ok:false,message:'لست عضواً في الغرفة.'});if(member.rows[0].is_muted)return res.status(403).json({ok:false,message:'تم كتمك في هذه الغرفة.'});const conv=await query('SELECT messaging_paused FROM conversations WHERE id=$1',[id]);if(!conv.rowCount)return res.status(404).json({ok:false,message:'الغرفة غير موجودة.'});if(conv.rows[0].messaging_paused&&!['admin','owner'].includes(req.user.role))return res.status(423).json({ok:false,message:'تم إيقاف إرسال الرسائل مؤقتاً.'});if(mediaId){const own=await query('SELECT 1 FROM media WHERE id=$1 AND owner_id=$2',[mediaId,req.user.id]);if(!own.rowCount)return res.status(403).json({ok:false,message:'المرفق غير صالح.'});}if(audioId){const own=await query('SELECT 1 FROM media WHERE id=$1 AND owner_id=$2',[audioId,req.user.id]);if(!own.rowCount)return res.status(403).json({ok:false,message:'المرفق الصوتي غير صالح.'});}const r=await transaction(async client=>{const m=await client.query('INSERT INTO messages(conversation_id,sender_id,body,media_id,audio_media_id) VALUES($1,$2,$3,$4,$5) RETURNING id,created_at',[id,req.user.id,body,mediaId,audioId]);await client.query('UPDATE conversation_members SET inbox_position_at=NOW(),last_read_message_id=$3 WHERE conversation_id=$1 AND user_id=$2',[id,req.user.id,m.rows[0].id]);await client.query("INSERT INTO activity_events(user_id,page,event_type,resource_type,resource_id) VALUES($1,'chat','send','conversation',$2)",[req.user.id,id]);return m.rows[0];});const payload={type:'chat_message',kind:'chat_message',conversation_id:id,id:Number(r.id),sender_id:req.user.id,full_name:req.user.full_name,body,media_id:mediaId,audio_media_id:audioId,created_at:r.created_at};await notify('lsu_events',payload);res.status(201).json({ok:true,message:payload});}catch(e){next(e)}});
  router.post('/chats/:id/read',requireAuth,async(req,res,next)=>{try{const id=Number(req.params.id),messageId=Number(req.body?.message_id||0);await query('UPDATE conversation_members SET last_read_message_id=GREATEST(COALESCE(last_read_message_id,0),$3) WHERE conversation_id=$1 AND user_id=$2',[id,req.user.id,messageId]);res.json({ok:true});}catch(e){next(e)}});
}
module.exports={router,attach};
