const express = require('express');
const multer = require('multer');
const { query, transaction, notify } = require('../db');
const { publicUser } = require('../security');

const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: Number(process.env.MAX_UPLOAD_BYTES || 5242880), files: 1 } });
const router = express.Router();

function parseHashtags(value) { const text=String(value||''); return [...new Set(text.split(/[\s,]+/).map(x=>x.trim().replace(/^#/,'').toLowerCase()).filter(x=>/^[\p{L}0-9_\-]{1,40}$/u.test(x)).slice(0,12))]; }
function postPayload(row){return {...row,id:Number(row.id),author_id:Number(row.author_id),likes:Number(row.likes||0),comments_count:Number(row.comments_count||0),liked_by_me:Boolean(row.liked_by_me),media_url:row.media_id?`/api/media/${row.media_id}`:(row.image_url||null),author:row.full_name?{id:Number(row.author_id),full_name:row.full_name,avatar_url:row.avatar_media_id?`/api/media/${row.avatar_media_id}`:(row.avatar_url||null)}:null,comments:(row.comments||[]).map(c=>({...c,id:Number(c.id),author_id:Number(c.author_id),avatar_url:c.avatar_media_id?`/api/media/${c.avatar_media_id}`:null}))};}
function listPosts(section,userId,limit,before){const values=[section,Math.min(Math.max(Number(limit)||20,1),50),before?new Date(before):null,userId?Number(userId):0];return query(`SELECT p.*,u.full_name,u.avatar_media_id,u.avatar_url,(SELECT COUNT(*) FROM post_likes pl WHERE pl.post_id=p.id) AS likes,(SELECT COUNT(*) FROM post_comments pc WHERE pc.post_id=p.id) AS comments_count,EXISTS(SELECT 1 FROM post_likes ml WHERE ml.post_id=p.id AND ml.user_id=$4) AS liked_by_me,COALESCE((SELECT json_agg(c ORDER BY c.created_at ASC) FROM (SELECT pc.id,pc.author_id,pc.body,pc.created_at,u2.full_name,u2.avatar_media_id FROM post_comments pc JOIN users u2 ON u2.id=pc.author_id WHERE pc.post_id=p.id ORDER BY pc.created_at ASC LIMIT 25)c),'[]'::json) AS comments FROM posts p JOIN users u ON u.id=p.author_id WHERE p.section=$1 AND p.is_published=TRUE AND ($3::timestamptz IS NULL OR p.created_at<$3) ORDER BY p.is_pinned DESC,p.created_at DESC,p.id DESC LIMIT $2`,values).then(r=>r.rows.map(postPayload));}
function attach(getUser,requireAuth){
router.get('/app-config',async(req,res,next)=>{try{const result=await query("SELECT key,value FROM app_settings WHERE key IN ('theme','features') ORDER BY key");const config={};result.rows.forEach(r=>config[r.key]=r.value);res.json({ok:true,config});}catch(e){next(e)}});
router.get('/home',async(req,res,next)=>{try{const u=getUser?await getUser(req):null;res.json({ok:true,posts:await listPosts('community',u?.id,20,null)});}catch(e){next(e)}});
router.get('/announcements',async(req,res,next)=>{try{const r=await query('SELECT * FROM announcements WHERE is_published=TRUE ORDER BY published_at DESC,id DESC LIMIT 100');res.json({ok:true,items:r.rows});}catch(e){next(e)}});
router.get('/activities',async(req,res,next)=>{try{const r=await query('SELECT * FROM activities WHERE is_published=TRUE ORDER BY event_date DESC NULLS LAST,created_at DESC LIMIT 100');res.json({ok:true,items:r.rows});}catch(e){next(e)}});
router.get('/schedule',async(req,res,next)=>{try{const r=await query('SELECT * FROM schedules WHERE is_published=TRUE ORDER BY day_name,start_time,id');res.json({ok:true,items:r.rows});}catch(e){next(e)}});
router.get('/posts',async(req,res,next)=>{try{const u=getUser?await getUser(req):null;res.json({ok:true,items:await listPosts(String(req.query.section||'community'),u?.id,req.query.limit,req.query.before)});}catch(e){next(e)}});
router.get('/media/:id',async(req,res,next)=>{try{const r=await query('SELECT mime_type,data FROM media WHERE id=$1 LIMIT 1',[Number(req.params.id)]);if(!r.rowCount)return res.status(404).end();res.setHeader('Content-Type',r.rows[0].mime_type);res.setHeader('Cache-Control','public,max-age=86400,immutable');res.setHeader('Content-Length',r.rows[0].data.length);res.end(r.rows[0].data);}catch(e){next(e)}});
router.post('/media',requireAuth,upload.single('file'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({ok:false,message:'اختر ملفاً.'});if(!/^image\/(jpeg|png|webp|gif)$/.test(req.file.mimetype))return res.status(415).json({ok:false,message:'يسمح بصور JPEG وPNG وWebP وGIF.'});const r=await query('INSERT INTO media(owner_id,mime_type,file_name,byte_size,data) VALUES($1,$2,$3,$4,$5) RETURNING id,mime_type,file_name,byte_size,created_at',[req.user.id,req.file.mimetype,req.file.originalname,req.file.size,req.file.buffer]);res.status(201).json({ok:true,media:{...r.rows[0],id:Number(r.rows[0].id),url:`/api/media/${r.rows[0].id}`}});}catch(e){next(e)}});
router.post('/posts',requireAuth,async(req,res,next)=>{try{const body=String(req.body?.body||'').trim(),title=String(req.body?.title||'').trim().slice(0,255),mediaId=req.body?.media_id?Number(req.body.media_id):null;if(!body)return res.status(400).json({ok:false,message:'اكتب محتوى المنشور.'});if(mediaId){const own=await query('SELECT 1 FROM media WHERE id=$1 AND owner_id=$2',[mediaId,req.user.id]);if(!own.rowCount)return res.status(403).json({ok:false,message:'لا تملك الملف المرفق.'});}const r=await query(`INSERT INTO posts(author_id,section,title,body,content_type,hashtags,media_id) VALUES($1,$2,$3,$4,'post',$5,$6) RETURNING id,created_at`,[req.user.id,String(req.body?.section||'community').slice(0,40),title||null,body,parseHashtags(req.body?.hashtags),mediaId]);await query('INSERT INTO activity_events(user_id,page,event_type,resource_type,resource_id) VALUES($1,$2,$3,$4,$5)',[req.user.id,'posts','create','post',r.rows[0].id]);await notify('lsu_events',{kind:'post_created',post_id:Number(r.rows[0].id)});res.status(201).json({ok:true,id:Number(r.rows[0].id)});}catch(e){next(e)}});
router.post('/posts/:id/like',requireAuth,async(req,res,next)=>{try{const id=Number(req.params.id),existing=await query('SELECT 1 FROM post_likes WHERE post_id=$1 AND user_id=$2',[id,req.user.id]);if(existing.rowCount)await query('DELETE FROM post_likes WHERE post_id=$1 AND user_id=$2',[id,req.user.id]);else await query('INSERT INTO post_likes(post_id,user_id) VALUES($1,$2)',[id,req.user.id]);const count=await query('SELECT COUNT(*)::int AS count FROM post_likes WHERE post_id=$1',[id]);res.json({ok:true,liked:!existing.rowCount,count:Number(count.rows[0].count)});}catch(e){next(e)}});
router.post('/posts/:id/comments',requireAuth,async(req,res,next)=>{try{const body=String(req.body?.body||'').trim().slice(0,2000);if(!body)return res.status(400).json({ok:false,message:'اكتب تعليقاً.'});const r=await query('INSERT INTO post_comments(post_id,author_id,body) VALUES($1,$2,$3) RETURNING id,created_at',[Number(req.params.id),req.user.id,body]);res.status(201).json({ok:true,comment:{id:Number(r.rows[0].id),author_id:req.user.id,full_name:req.user.full_name,body,created_at:r.rows[0].created_at}});}catch(e){next(e)}});
router.post('/posts/:id/report',requireAuth,async(req,res,next)=>{try{const reason=String(req.body?.reason||'محتوى مخالف').slice(0,255),details=String(req.body?.details||'').slice(0,2000);const r=await query('INSERT INTO reports(reporter_id,target_type,target_id,reason,details) VALUES($1,\'post\',$2,$3,$4) RETURNING id',[req.user.id,Number(req.params.id),reason,details]);res.status(201).json({ok:true,id:Number(r.rows[0].id)});}catch(e){next(e)}});
router.get('/profile/:id',async(req,res,next)=>{try{const viewer=getUser?await getUser(req):null,r=await query('SELECT * FROM users WHERE id=$1 AND is_active=TRUE LIMIT 1',[Number(req.params.id)]);if(!r.rowCount)return res.status(404).json({ok:false,message:'Profile not found.'});res.json({ok:true,user:publicUser(r.rows[0],viewer?.id)});}catch(e){next(e)}});
router.put('/profile',requireAuth,async(req,res,next)=>{try{const fields=[],values=[],allowed=['full_name','phone','academic_year','bio','email'];for(const key of allowed)if(req.body?.[key]!==undefined){let v=String(req.body[key]??'').trim();if(key==='full_name'&&(!v||v.length>150))return res.status(400).json({ok:false,message:'الاسم غير صالح.'});if(key==='bio')v=v.slice(0,5000);fields.push(`${key}=$${values.length+1}`);values.push(v||null);}if(req.body?.privacy_settings!==undefined){fields.push(`privacy_settings=$${values.length+1}`);values.push(JSON.stringify(req.body.privacy_settings||{}));}if(req.body?.notification_settings!==undefined){fields.push(`notification_settings=$${values.length+1}`);values.push(JSON.stringify(req.body.notification_settings||{}));}if(!fields.length)return res.json({ok:true,user:publicUser(req.user,req.user.id)});values.push(req.user.id);const r=await query(`UPDATE users SET ${fields.join(',')} WHERE id=$${values.length} RETURNING *`,values);res.json({ok:true,user:publicUser(r.rows[0],req.user.id)});}catch(e){next(e)}});
router.get('/polls',async(req,res,next)=>{try{const r=await query(`SELECT p.*,COALESCE((SELECT COUNT(*) FROM poll_votes v WHERE v.poll_id=p.id),0)::int AS votes FROM polls p ORDER BY p.created_at DESC LIMIT 50`);res.json({ok:true,items:r.rows});}catch(e){next(e)}});
router.post('/polls',requireAuth,async(req,res,next)=>{try{const question=String(req.body?.question||'').trim().slice(0,500),options=Array.isArray(req.body?.options)?req.body.options.map(x=>String(x).trim()).filter(Boolean).slice(2,8):[];if(!question||options.length<2)return res.status(400).json({ok:false,message:'السؤال وخياران على الأقل مطلوبان.'});const close=Number(req.body?.duration_minutes||1440);const r=await query(`INSERT INTO polls(author_id,question,options,hashtags,closes_at) VALUES($1,$2,$3,$4,NOW()+($5*INTERVAL '1 minute')) RETURNING id`,[req.user.id,question,JSON.stringify(options),parseHashtags(req.body?.hashtags),Math.min(Math.max(close,5),10080)]);res.status(201).json({ok:true,id:Number(r.rows[0].id)});}catch(e){next(e)}});
router.post('/polls/:id/vote',requireAuth,async(req,res,next)=>{try{const idx=Number(req.body?.option_index);if(!Number.isInteger(idx)||idx<0||idx>20)return res.status(400).json({ok:false,message:'الخيار غير صالح.'});const poll=await query('SELECT closes_at FROM polls WHERE id=$1',[Number(req.params.id)]);if(!poll.rowCount)return res.status(404).json({ok:false,message:'Poll not found.'});if(poll.rows[0].closes_at&&new Date(poll.rows[0].closes_at)<new Date())return res.status(409).json({ok:false,message:'انتهى التصويت.'});await query(`INSERT INTO poll_votes(poll_id,user_id,option_index) VALUES($1,$2,$3) ON CONFLICT(poll_id,user_id) DO UPDATE SET option_index=EXCLUDED.option_index,created_at=NOW()`,[Number(req.params.id),req.user.id,idx]);res.json({ok:true});}catch(e){next(e)}});
}
module.exports={router,attach};
