const crypto=require('crypto');
const SESSION_COOKIE='lsu_session';
const hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
const hashDevice=v=>hash((process.env.APP_DEVICE_SALT||'change-device-salt')+'|'+String(v||'unknown'));
const token=()=>crypto.randomBytes(32).toString('base64url');
function hashPassword(password){return new Promise((resolve,reject)=>{const salt=crypto.randomBytes(16).toString('hex');crypto.scrypt(String(password),salt,64,{N:16384,r:8,p:1},(e,d)=>e?reject(e):resolve(salt+':'+d.toString('hex')))});}
function verifyPassword(password,stored){return new Promise((resolve,reject)=>{const [salt,keyHex]=String(stored||'').split(':');if(!salt||!keyHex)return resolve(false);const expected=Buffer.from(keyHex,'hex');crypto.scrypt(String(password),salt,expected.length,{N:16384,r:8,p:1},(e,d)=>e?reject(e):resolve(expected.length===d.length&&crypto.timingSafeEqual(expected,d)))});}
function parseCookies(header){const out={};for(const part of String(header||'').split(';')){const i=part.indexOf('=');if(i<0)continue;try{out[decodeURIComponent(part.slice(0,i).trim())]=decodeURIComponent(part.slice(i+1).trim())}catch{}}return out}
function getToken(req){const auth=String(req.headers.authorization||'');if(auth.startsWith('Bearer '))return auth.slice(7).trim()||null;return parseCookies(req.headers.cookie)[SESSION_COOKIE]||null}
function setSessionCookie(res,value){let s=SESSION_COOKIE+'='+encodeURIComponent(value)+'; HttpOnly; Path=/; SameSite=Lax; Max-Age=2592000';if(process.env.NODE_ENV==='production')s+='; Secure';res.setHeader('Set-Cookie',s)}
function clearSessionCookie(res){let s=SESSION_COOKIE+'=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0';if(process.env.NODE_ENV==='production')s+='; Secure';res.setHeader('Set-Cookie',s)}
function publicUser(u,viewerId){if(!u)return null;const self=Number(viewerId)===Number(u.id),ownerHidden=u.role==='owner'&&!self,privacy=u.privacy_settings||{},online=u.last_seen_at?(Date.now()-new Date(u.last_seen_at).getTime()<90000):false;return{id:Number(u.id),full_name:ownerHidden?'عضو الاتحاد':u.full_name,student_id:ownerHidden?null:u.student_id,email:ownerHidden||(!self&&!privacy.show_email)?null:u.email,phone:ownerHidden||(!self&&!privacy.show_phone)?null:u.phone,academic_year:u.academic_year,bio:ownerHidden?null:u.bio,avatar_url:u.avatar_media_id?'/api/media/'+u.avatar_media_id:(u.avatar_url||null),cover_url:u.cover_media_id?'/api/media/'+u.cover_media_id:(u.profile_background_url||null),privacy_settings:privacy,notification_settings:u.notification_settings||{},role:ownerHidden?'member':u.role,is_active:Boolean(u.is_active),online:self||privacy.show_online!==false?online:false,last_seen_at:self||privacy.show_online!==false?u.last_seen_at:null,current_page:self?u.current_page:null,created_at:u.created_at,last_login:self?u.last_login:null}}
module.exports={hash,hashDevice,token,hashPassword,verifyPassword,parseCookies,getToken,setSessionCookie,clearSessionCookie,publicUser};