import 'localization.dart';
import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'api.dart';
import 'user_management_screen.dart';
import 'permission_matrix_screen.dart';
import 'hub_configurator_screen.dart';
import 'audit_log_screen.dart';
import 'mfa_setup_screen.dart';

void main()=>runApp(AdminLanguageScope(controller:AdminLanguageController(),child:const AdminApp()));
class AdminApp extends StatelessWidget{const AdminApp({super.key});@override Widget build(BuildContext c){final lang=AdminLanguageScope.of(c);return ValueListenableBuilder<Locale>(valueListenable:lang,builder:(context,locale,_)=><MaterialApp(title:AdminL10n.t(context,'title'),debugShowCheckedModeBanner:false,locale:locale,supportedLocales:const[Locale('en'),Locale('ar')],theme:ThemeData.dark(useMaterial3:true).copyWith(colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFF8B5CF6),brightness:Brightness.dark)),home:const AdminLogin()));}}
class AdminLogin extends StatefulWidget{const AdminLogin({super.key});@override State<AdminLogin> createState()=>_AdminLoginState();}
class _AdminLoginState extends State<AdminLogin>{final u=TextEditingController(),p=TextEditingController(),o=TextEditingController();bool mfa=false,busy=false;String? error;Future<void> login()async{setState(()=>busy=true);try{await adminApi.login(u.text.trim(),p.text,otp:mfa?o.text.trim():null);if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const CommandCenter()));}on MfaNeeded{setState(()=>mfa=true);}catch(_){setState(()=>error='Authentication failed.');}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext c)=>Scaffold(body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:420),child:Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.balance,size:52,color:Color(0xFF8B5CF6)),const Text('Union Admin Command Center',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),TextField(controller:u,decoration:const InputDecoration(labelText:'Username')),TextField(controller:p,obscureText:true,decoration:const InputDecoration(labelText:'Password')),if(mfa)TextField(controller:o,keyboardType:TextInputType.number,maxLength:6,decoration:const InputDecoration(labelText:'TOTP code')),if(error!=null)Text(error!,style:const TextStyle(color:Colors.redAccent)),const SizedBox(height:16),SizedBox(width:double.infinity,child:ElevatedButton(onPressed:busy?null:login,child:Text(busy?'Signing in…':'Sign in')),),TextButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const BootstrapMfa())),child:const Text('First-time Agent MFA enrollment'))])))));}}
class BootstrapMfa extends StatefulWidget{const BootstrapMfa({super.key});@override State<BootstrapMfa> createState()=>_BootstrapMfaState();}
class _BootstrapMfaState extends State<BootstrapMfa>{final token=TextEditingController(),u=TextEditingController(),p=TextEditingController(),code=TextEditingController();String? uri,msg;Future<void> setup()async{try{uri=await adminApi.bootstrapMfa(token.text,u.text,p.text);setState((){});}catch(_){setState(()=>msg='Enrollment request failed. Check the bootstrap token and Agent credentials.');}}Future<void> confirm()async{try{await adminApi.bootstrapConfirm(token.text,u.text,p.text,code.text);setState(()=>msg='MFA enabled. You can now sign in normally.');}catch(_){setState(()=>msg='Invalid TOTP code.');}}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Initial Agent MFA')),body:ListView(padding:const EdgeInsets.all(20),children:[TextField(controller:token,obscureText:true,decoration:const InputDecoration(labelText:'One-time bootstrap token')),TextField(controller:u,decoration:const InputDecoration(labelText:'Agent username')),TextField(controller:p,obscureText:true,decoration:const InputDecoration(labelText:'Agent password')),ElevatedButton(onPressed:setup,child:const Text('Generate MFA enrollment')),if(uri!=null)...[QrImageView(data:uri!,size:220),SelectableText(uri!),TextField(controller:code,keyboardType:TextInputType.number,maxLength:6,decoration:const InputDecoration(labelText:'Authenticator code')),ElevatedButton(onPressed:confirm,child:const Text('Confirm and enable MFA'))],if(msg!=null)Text(msg!) ]);}}
class CommandCenter extends StatefulWidget{const CommandCenter({super.key});@override State<CommandCenter> createState()=>_CommandCenterState();}
class _CommandCenterState extends State<CommandCenter>{int i=0;final pages=const[UserManagementScreen(),PermissionMatrixScreen(),HubConfiguratorScreen(),AuditLogScreen(),MfaSetupScreen()];@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(AdminL10n.t(c,'title')),actions:[IconButton(onPressed:AdminLanguageScope.of(c).toggle,icon:const Icon(Icons.language)),[IconButton(onPressed:()=>adminApi.logout().then((_)=>Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const AdminLogin()),(_)=>false)),icon:const Icon(Icons.logout))]),body:pages[i],bottomNavigationBar:NavigationBar(selectedIndex:i,onDestinationSelected:(v)=>setState(()=>i=v),destinations:const[NavigationDestination(icon:Icon(Icons.people),label:'Users'),NavigationDestination(icon:Icon(Icons.security),label:'Permissions'),NavigationDestination(icon:Icon(Icons.hub),label:'Hubs'),NavigationDestination(icon:Icon(Icons.receipt_long),label:'Audit'),NavigationDestination(icon:Icon(Icons.lock),label:'MFA')]);}}
