name: law_union_client
description: Law Faculty Student Union student and community client.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  web_socket_channel: ^3.0.2
flutter:
  uses-material-design: true
